Rezervace_Ples/Controllers/RezervaceController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Storage;
using Rezervace_Ples.Models;
using Rezervace_Ples.Models.Services;
using System.Data;

namespace Rezervace_Ples.Controllers
{
    public class RezervaceController : Controller
    {
        private StulService stolyService;
        private LidiService lidiService;
        private int isAdmin;

        public RezervaceController()
        {
            stolyService = new StulService();
            lidiService = new LidiService();
        }

        [HttpGet]
        public FileResult ExportPeopleInExcel()
        {
            var people = lidiService.GetCompleteList();
            var fileName = "list.xlsx";
            return GenerateExcel(fileName, people);
        }

        private FileResult GenerateExcel(string fileName, IEnumerable<Lidi> lidi)
        {
            DataTable dataTable = new DataTable("Lidi");
            dataTable.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("ID"),
                new DataColumn("Name"),
                new DataColumn("SurName"),
                new DataColumn("Stul"),
            });

            foreach (var clovek in lidi)
            {
                dataTable.Rows.Add(clovek.ID_Lidi, clovek.Name, clovek.Surname, clovek.ID_Stul);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dataTable);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                }
            }
        }

        public IActionResult Prizemi()
        {
            NastavitViewBagData("Prizemi");
            return View();
        }
       
        public IActionResult Balkon()
        {
            NastavitViewBagData("Balkon");
            return View();
        }

        public IActionResult StulDetail(int IDStolu)
        {
            Stul vybranyStul = stolyService.GetStul(IDStolu);

            var lidiList = lidiService.GetList(IDStolu);
            this.ViewBag.lidi = lidiList;

            
            this.ViewBag.stul = vybranyStul;

            int volnaMista = lidiService.GetVolnaMista(vybranyStul.ID_Stul);
            vybranyStul.ZbyvajiciMista = volnaMista;

            this.ViewBag.id = IDStolu;

            this.ViewBag.Text = sklonovaniSlovaMisto(volnaMista);
            this.ViewBag.TextVolne = sklonovaniSlovaVolne(volnaMista);

            return View();
        }

        [HttpGet]
        public IActionResult Create(int IDStolu)
        {
            int maxPocet = lidiService.GetVolnaMista(IDStolu);
            if (maxPocet == 0)
            {
                return RedirectToAction("StulDetail", new { IDStolu = IDStolu });
            }
            ViewBag.id = IDStolu;
            ViewBag.MaxPocet = maxPocet;

            var model = new KolikratNovyClovekModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(int IDStolu, KolikratNovyClovekModel zaznam)
        {
            ViewBag.id = IDStolu;
            if (ModelState.IsValid)
            {
                lidiService.Add(zaznam, IDStolu);
                return RedirectToAction("StulDetail", new { IDStolu = IDStolu });
            }

            return View(zaznam);
        }

        [HttpGet]
        public IActionResult Update(int id, int IDStolu)        
        {
            ViewBag.IDStolu = IDStolu;
            ViewBag.id = id;
            return View(lidiService.GetClovek(id));
        }

        [HttpPost]
        public IActionResult Update(Lidi clovek, int id, int IDStolu)
        {
            ViewBag.IDStolu = IDStolu;
            ViewBag.id = id;
            if (ModelState.IsValid)
            {
                lidiService.Update(clovek, id);
                return RedirectToAction("StulDetail", new { IDStolu = IDStolu });
            }
            return View(clovek);
        }

        [HttpGet]
        public IActionResult Delete(int id, int IDStolu)
        {
            lidiService.Delete(lidiService.GetClovek(id));
            return RedirectToAction("StulDetail", new { IDStolu = IDStolu });
        }

        [HttpGet]
        public IActionResult Zrusit(int IDStolu)
        {
            return RedirectToAction("StulDetail", new { IDStolu = IDStolu });
        }

        private void NastavitViewBagData(string akce)
        {
            isAdmin = (int)HttpContext.Session.GetInt32("Admin");
            var stolyList = akce == "Balkon" ? stolyService.StolyVrchniList() : stolyService.StolySpodniList();
            ViewBag.listStoly = stolyList;

            int celkovaZbyvajiciMista = 0;
            int celkovaMista = 0;

            foreach (var item in stolyList)
            {
                int volnaMista = lidiService.GetVolnaMista(item.ID_Stul);
                item.ZbyvajiciMista = volnaMista;

                celkovaZbyvajiciMista += item.ZbyvajiciMista;
                celkovaMista += item.PocetMist;
            }

            ViewBag.mistCelkem = celkovaMista;
            ViewBag.volnychMistCelkem = celkovaZbyvajiciMista;
            ViewBag.Admin = isAdmin;

            ViewBag.Text = sklonovaniSlovaMisto(celkovaZbyvajiciMista);
            ViewBag.TextVolne = sklonovaniSlovaVolne(celkovaZbyvajiciMista);
        }

        public string sklonovaniSlovaMisto(int cislo)
        {
            if (cislo == 1)
            {
                return $"místo";
            }
            else if (cislo >= 2 && cislo <= 4)
            {
                return $"místa";
            }
            else
            {
                return $"míst";
            }
        }

        public string sklonovaniSlovaVolne(int cislo)
        {
            if (cislo == 1)
            {
                return $"volné";
            }
            else if (cislo >= 2 && cislo <= 4)
            {
                return $"volná";
            }
            else
            {
                return $"volných";
            }
        }
    }
}

Rezervace_Ples/Views/Rezervace/Balkon.cshtml
<link rel="stylesheet" href="~/css/LogedStyle.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/vrsek.css" asp-append-version="true" />

@if (ViewBag.Admin == 1)
{
    <div id="container">
        <img src="/css/Planky/Farplan balkon (1).jpg" class="planek">
        <div class="pravyPanel">
            <div class="nadpis">
                <h1>Stoly - 1. patro</h1>
                <h2>@ViewBag.TextVolne @ViewBag.volnychMistCelkem @ViewBag.Text z @ViewBag.mistCelkem</h2>
            </div>
            <div class="ButtonyContainer">
                @foreach (Stul stul in ViewBag.listStoly)
                {
                    @if(stul.ZbyvajiciMista == 0)
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: red; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                    else if(stul.ZbyvajiciMista == stul.PocetMist)
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: green; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                    else
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: orange; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                }
            </div>
            <div class="VyberPodlazi">
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Prizemi">Přízemí</a>
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Balkon">1. patro</a>
                <a class="VyberButton" asp-action="ExportPeopleInExcel">Exportovat</a>
            </div>
        </div>
    </div>
}
else
{
    <div id="container">
        <img src="/css/Planky/Farplan balkon (1).jpg" class="planek">
        <div class="pravyPanel">
            <div class="nadpis">
                <h1>Stoly - 1. patro</h1>
                <h2>@ViewBag.TextVolne @ViewBag.volnychMistCelkem @ViewBag.Text z @ViewBag.mistCelkem</h2>
            </div>
            <div class="ButtonyContainer">
                @foreach (Stul stul in ViewBag.listStoly)
                {
                   
                    @if (stul.ZbyvajiciMista == 0)
                    {
                        <div class="stul" style="background: red; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                    else if (stul.ZbyvajiciMista == stul.PocetMist)
                    {
                        <div class="stul" style="background: green; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                    else
                    {
                        <div class="stul" style="background: orange; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                }
            </div>
            <div class="VyberPodlazi">
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Prizemi">Přízemí</a>
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Balkon">1. patro</a>
            </div>
        </div>
    </div>
}

Rezervace_Ples/Views/Rezervace/Create.cshtml
@model KolikratNovyClovekModel;

<link rel="stylesheet" href="~/css/createUpdate.css" asp-append-version="true" />

<div class="formContainer">
    <form asp-action="@ViewBag.Target" method="post">
        <label asp-for="Jmeno">
            Jméno: <input asp-for="Jmeno" type="text">
        </label>

        <label asp-for="Prijmeni">
            Přijmení: <input asp-for="Prijmeni" type="text">
        </label>

        <label asp-for="KolikratValue">
            Kolikrát vytvořit záznam: <input asp-for="KolikratValue" type="number" min="1" max="@ViewBag.MaxPocet" />
        </label>

        <div id="buttony">
            <button type="submit" asp-route-IDStolu="@ViewBag.id">Uložit</button>
            <a class="acko" asp-controller="Rezervace" asp-action="Zrusit" asp-route-IDStolu="@ViewBag.id">Zrušit</a>
        </div>
    </form>
</div>

Rezervace_Ples/Views/Rezervace/Kolikrat.cshtml
@model KolikratNovyClovekModel;
<link rel="stylesheet" href="~/css/Kolikrat.css" asp-append-version="true" />

<div class="formContainer">
    <form asp-controller="Rezervace" asp-action="Kolikrat" method="post">
        <label asp-for="KolikratValue">
            Kolikrát vytvořit záznam: <input asp-for="KolikratValue" type="number" min="1" max="@ViewBag.MaxPocet"/>
        </label>
        <div id="buttonCont">
            <button type="submit" class="btn btn-primary" style="background: green; color: white; border: black;">Potvrdit</button>
        </div>
    </form>
</div>

Rezervace_Ples/Views/Rezervace/Prizemi.cshtml
<link rel="stylesheet" href="~/css/LogedStyle.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/spodek.css" asp-append-version="true" />
@if (ViewBag.Admin == 1)
{
    <div id="container">
        <img src="/css//Planky/FARPLÁN VELKÝ SÁL (1).jpg" class="planek">
        <div class="pravyPanel">
            <div class="nadpis">
                <h1>Stoly - přízemí</h1>
                <h2>@ViewBag.TextVolne @ViewBag.volnychMistCelkem @ViewBag.Text ze @ViewBag.mistCelkem</h2>
            </div>
            <div class="ButtonyContainer">
                @foreach (Stul stul in ViewBag.listStoly)
                {
                    @if (stul.ZbyvajiciMista == 0)
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: red; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                    else if (stul.ZbyvajiciMista == stul.PocetMist)
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: green; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                    else
                    {
                        <a class="stul" asp-controller="Rezervace" asp-action="StulDetail" asp-route-IDStolu="@stul.ID_Stul" style="background: orange; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></a>
                    }
                }
            </div>
            <div class="VyberPodlazi">
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Prizemi">Přízemí</a>
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Balkon">1. patro</a>
                <a class="VyberButton" asp-action="ExportPeopleInExcel">Exportovat</a>
            </div>
        </div>
    </div>
}
else
{
    <div id="container">
        <img src="/css//Planky/FARPLÁN VELKÝ SÁL (1).jpg" class="planek">
        <div class="pravyPanel">
            <div class="nadpis">
                <h1>Stoly - přízemí</h1>
                <h2>@ViewBag.TextVolne @ViewBag.volnychMistCelkem @ViewBag.Text ze @ViewBag.mistCelkem</h2>
            </div>
            <div class="ButtonyContainer">
                @foreach (Stul stul in ViewBag.listStoly)
                {
                    @if (stul.ZbyvajiciMista == 0)
                    {
                        <div class="stul" style="background: red; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                    else if (stul.ZbyvajiciMista == stul.PocetMist)
                    {
                        <div class="stul" style="background: green; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                    else
                    {
                        <div class="stul" style="background: orange; color: white;"><bold>Stůl: @stul.ID_Stul</bold> <span>(@stul.ZbyvajiciMista z @stul.PocetMist)</span></div>
                    }
                }
            </div>
            <div class="VyberPodlazi">
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Prizemi">Přízemí</a>
                <a class="VyberButton" asp-controller="Rezervace" asp-action="Balkon">1. patro</a>
            </div>
        </div>
    </div>
}

Rezervace_Ples/Views/Rezervace/StulDetail.cshtml
@model Lidi;

<link rel="stylesheet" href="~/css/stulId.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/LogedStyle.css" asp-append-version="true" />

<div id="plocha">
    <h1 class="nadpisStolu">Stůl @ViewBag.stul.ID_Stul</h1>
    <h2 class="pocetMist" style="color: darkslateblue">@ViewBag.TextVolne @ViewBag.stul.ZbyvajiciMista @ViewBag.Text z @ViewBag.stul.PocetMist</h2>
    <div id="tableContainer">
        <table>
            <thead>
                <tr>
                    <th>Jméno</th>
                    <th>Přijmení</th>
                    <th></th>
                    <th>
                        <a asp-controller="Rezervace" asp-action="Create" asp-route-IDStolu="@ViewBag.id" class="btn btn-primary" style="background: royalblue; color: white; border: black;">Vytvořit</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Lidi clovek in ViewBag.lidi)
                {
                    <tr>
                        <td><h3 class="jmeno">@clovek.Name</h3></td>
                        <td><h3 class="prijmeni">@clovek.Surname</h3></td>
                        <td>
                            <a class="acko delete" asp-controller="Rezervace" asp-action="Delete" asp-route-id="@clovek.ID_Lidi" asp-route-IDStolu="@clovek.ID_Stul" class="btn btn-primary" style="background: darkred; color: white; border: black;">Odstranit</a>
                        </td>
                        <td>
                            <a class="acko upravit" asp-controller="Rezervace" asp-action="Update" asp-route-id="@clovek.ID_Lidi" asp-route-IDStolu="@clovek.ID_Stul" class="btn btn-primary" style="background: green; color: white; border: black;">Upravit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
  

    <div id="containerNabidka">
        <div id="nabidka">
            <a class="VyberButton" asp-controller="Rezervace" asp-action="Prizemi">Přízemí</a>
            <a class="VyberButton" asp-controller="Rezervace" asp-action="Balkon">1. patro</a>
        </div>
    </div>
</div>

Rezervace_Ples/Views/Rezervace/Update.cshtml
@model Lidi;

<link rel="stylesheet" href="~/css/createUpdate.css" asp-append-version="true" />

<div class="formContainer">
    <form asp-action="@ViewBag.Target" method="post">
        <label asp-for="Name">
            Jméno: <input asp-for="Name" type="text">
        </label>

        <label asp-for="Surname">
            Přijmení: <input asp-for="Surname" type="text">
        </label>

        <div id="buttony">
            <button type="submit" asp-route-IDStolu="@ViewBag.IDStolu" asp-route-id="@ViewBag.id">Uložit</button>
            <a class="acko" asp-controller="Rezervace" asp-action="Zrusit" asp-route-IDStolu="@ViewBag.IDStolu">Zrušit</a>
        </div>
    </form>
</div>